<a href="https://colab.research.google.com/github/elevano1/UTEC_Phyton/blob/main/modulo-II/_7__python_utec_161224_17122024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
# Llamar a la librería
import numpy as np

In [2]:
# Crear un arreglo en numpy
arr_1 = np.array([2,4,6])

In [3]:
# Visualizar el arreglo
print(f"El arreglo en numpy es \n{arr_1}")

El arreglo en numpy es 
[2 4 6]


In [4]:
# Crear una lista
lista_1 = [2,4,6]
print(f"La lista es \n{lista_1}")

La lista es 
[2, 4, 6]


In [5]:
print(f"El objeto arr_1 es del tipo \n{type(arr_1)}")
print(f"\nEl objeto lista_1 es del tipo \n{type(lista_1)}")

El objeto arr_1 es del tipo 
<class 'numpy.ndarray'>

El objeto lista_1 es del tipo 
<class 'list'>


In [6]:
# Operaciones listas
print(f"El valor mínimo de la lista \n{lista_1} es {min(lista_1)}")
print(f"\nEl valor máximo de la lista \n{lista_1} es {max(lista_1)}")
print(f"\nLa suma total de la lista \n{lista_1} es {sum(lista_1)}")

El valor mínimo de la lista 
[2, 4, 6] es 2

El valor máximo de la lista 
[2, 4, 6] es 6

La suma total de la lista 
[2, 4, 6] es 12


In [7]:
# El símbolo "+" permite concatenar listas
lista_1 + [5]

[2, 4, 6, 5]

In [8]:
print(f"El arreglo en numpy es \n{arr_1}")
print(f"Suma del arreglo en numpy con 5 es \n{arr_1 + 5}")

El arreglo en numpy es 
[2 4 6]
Suma del arreglo en numpy con 5 es 
[ 7  9 11]


In [9]:
# Crear arreglos de numpy

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(f"El arreglo a1 es \n{a1}")
print(f"\nEl arreglo a2 es \n{a2}")

El arreglo a1 es 
[1 2 3]

El arreglo a2 es 
[4 5 6]


In [10]:
print(f"El arreglo a1 es del tipo \n{type(a1)}")
print(f"\nEl arreglo a2 es del tipo \n{type(a2)}")

El arreglo a1 es del tipo 
<class 'numpy.ndarray'>

El arreglo a2 es del tipo 
<class 'numpy.ndarray'>


In [11]:
# Operaciones matemáticas con los arreglos de numpy
arr_sum = a1 + a2
arr_prod = a1 * a2
print(f"La suma de los arreglos es \n{arr_sum}")
print(f"\nLa multiplicación de los arreglos es \n{arr_prod}")

La suma de los arreglos es 
[5 7 9]

La multiplicación de los arreglos es 
[ 4 10 18]


In [12]:
# Matrices de 2D
mat_4 = np.array([[1,2,3],[4,5,6]])
print(f"La matriz de 2D es \n{mat_4}")

La matriz de 2D es 
[[1 2 3]
 [4 5 6]]


In [13]:
# Crear una lista de listas
ll_1 = [[10,20,30],[10,10,10]]
print(f"La lista de listas es \n{ll_1}")
print(f"\nEl objeto ll_1 es del tipo \n{type(ll_1)}")

La lista de listas es 
[[10, 20, 30], [10, 10, 10]]

El objeto ll_1 es del tipo 
<class 'list'>


In [14]:
# Crear una matriz en numpy a partir de una lista

mat_6 = np.array(ll_1)
print(f"La matriz de 2D es \n{mat_6}")
print(f"\nEl objeto mat_6 es del tipo \n{type(mat_6)}")

La matriz de 2D es 
[[10 20 30]
 [10 10 10]]

El objeto mat_6 es del tipo 
<class 'numpy.ndarray'>


In [15]:
# Creamos una matriz 1D a parit de arange
mat_7 = np.arange(15)
print(f"La matriz 1D de numpy es \n{mat_7}")
print(f"\nEl objeto mat_7 es del tipo \n{type(mat_7)}")

La matriz 1D de numpy es 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

El objeto mat_7 es del tipo 
<class 'numpy.ndarray'>


In [16]:
# Crear una matriz 2D en numpy a partir de una matriz 1D
mat_8 = mat_7.reshape(3,5) #3 filas, 5 columnas
print(f"La matriz 2D de numpy es \n{mat_8}")
print(f"\nEl objeto mat_8 es del tipo \n{type(mat_8)}")

La matriz 2D de numpy es 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

El objeto mat_8 es del tipo 
<class 'numpy.ndarray'>


In [17]:
print(f"El número de dimensiones del objeto mat_8 es {mat_8.ndim}")
print(f"\nEl tamaño de las dimensiones del objeto mat_8 es {mat_8.shape}")
print(f"\nEl número de elementos del objeto mat_8 es {mat_8.size}")

El número de dimensiones del objeto mat_8 es 2

El tamaño de las dimensiones del objeto mat_8 es (3, 5)

El número de elementos del objeto mat_8 es 15


In [18]:
# Crear una matriz de ceros con determinadas dimensiones
mat_9 = np.zeros((4,3))

In [19]:
# Las características de la matriz
print(f"La matriz mat_9 es \n{mat_9}")
print(f"\nEl objeto mat_9 es del tipo \n{type(mat_9)}")
print(f"\nEl número de dimensiones de la matriz mat_9 es {mat_9.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_9 es {mat_9.shape}")
print(f"\nEl número de elementos de la matriz mat_9 es {mat_9.size}")

La matriz mat_9 es 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

El objeto mat_9 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_9 es 2

El tamaño de las dimensiones de la matriz mat_9 es (4, 3)

El número de elementos de la matriz mat_9 es 12


In [20]:
# Crear una matriz de valores espaciados en un intervalo
mat_10 = np.linspace(50,60,20)
# Las características de la matriz
print(f"La matriz mat_10 es \n{mat_10}")
print(f"\nEl objeto mat_10 es del tipo \n{type(mat_10)}")
print(f"\nEl número de dimensiones de la matriz mat_10 es {mat_10.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_10 es {mat_10.shape}")
print(f"\nEl número de elementos de la matriz mat_10 es {mat_10.size}")

La matriz mat_10 es 
[50.         50.52631579 51.05263158 51.57894737 52.10526316 52.63157895
 53.15789474 53.68421053 54.21052632 54.73684211 55.26315789 55.78947368
 56.31578947 56.84210526 57.36842105 57.89473684 58.42105263 58.94736842
 59.47368421 60.        ]

El objeto mat_10 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_10 es 1

El tamaño de las dimensiones de la matriz mat_10 es (20,)

El número de elementos de la matriz mat_10 es 20


In [21]:
l_0 = [30,32,40,50,65]
print(f"El objeto l_0 es {l_0}")
print(f"El objeto l_0 es del tipo {type(l_0)}")

El objeto l_0 es [30, 32, 40, 50, 65]
El objeto l_0 es del tipo <class 'list'>


In [22]:
mat_11 = np.array(l_0) # Convertir una lista en un arreglo numpy
print(f"El objeto mat_11 es {mat_11}")
print(f"El objeto mat_11 es del tipo {type(mat_11)}")

El objeto mat_11 es [30 32 40 50 65]
El objeto mat_11 es del tipo <class 'numpy.ndarray'>


In [23]:
# Las características de la matriz
print(f"La matriz mat_11 es \n{mat_11}")
print(f"\nEl objeto mat_11 es del tipo \n{type(mat_11)}")
print(f"\nEl número de dimensiones de la matriz mat_11 es {mat_11.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_11 es {mat_11.shape}")
print(f"\nEl número de elementos de la matriz mat_11 es {mat_11.size}")

La matriz mat_11 es 
[30 32 40 50 65]

El objeto mat_11 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_11 es 1

El tamaño de las dimensiones de la matriz mat_11 es (5,)

El número de elementos de la matriz mat_11 es 5


In [24]:
import numpy as np
mat_12 = np.arange(24).reshape(2,4,3)
# Las características de la matriz
print(f"La matriz mat_12 es \n{mat_12}")
print(f"\nEl objeto mat_12 es del tipo \n{type(mat_12)}")
print(f"\nEl número de dimensiones de la matriz mat_12 es {mat_12.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_12 es {mat_12.shape}")
print(f"\nEl número de elementos de la matriz mat_12 es {mat_12.size}")

La matriz mat_12 es 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

El objeto mat_12 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_12 es 3

El tamaño de las dimensiones de la matriz mat_12 es (2, 4, 3)

El número de elementos de la matriz mat_12 es 24


In [25]:
print(f"\nEl número de dimensiones de la matriz mat_12 es {mat_12.ndim}") # Matriz de 3D
print(f"\nLa matriz mat_12 se convierte con la función ravel en \n{mat_12.ravel()}")
mat_12 = mat_12.ravel()


El número de dimensiones de la matriz mat_12 es 3

La matriz mat_12 se convierte con la función ravel en 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [26]:
print(f"\nEl número de dimensiones de la matriz mat_12 es {mat_12.ndim}")


El número de dimensiones de la matriz mat_12 es 1


In [28]:
# np.array(objeto) => objeto se convierte en numpy array
ll_x = [[57,21,48,0],[71,27,60,0],[111,51,96,0]]
print(f"La lista de listas es \n{ll_x}")

La lista de listas es 
[[57, 21, 48, 0], [71, 27, 60, 0], [111, 51, 96, 0]]


In [29]:
mat_13 = np.array(ll_x)
print(f"La matriz mat_13 es \n{mat_13}")

La matriz mat_13 es 
[[ 57  21  48   0]
 [ 71  27  60   0]
 [111  51  96   0]]


In [30]:
mat_13 = np.array([
    [  # Primera matriz
        [57, 21, 48, 0],
        [71, 27, 60, 0],
        [111, 51, 96, 0]
    ],
    [  # Segunda matriz
        [66, 16, 36, 18],
        [95, 22, 58, 29],
        [83, 20, 46, 23]
    ],
    [  # Tercera matriz
        [44, 34, 72, 44],
        [34, 32, 72, 34],
        [13, 25, 64, 13]
    ]
])

In [31]:
# Las características de la matriz
print(f"La matriz mat_13 es \n{mat_13}")
print(f"\nEl objeto mat_13 es del tipo \n{type(mat_13)}")
print(f"\nEl número de dimensiones de la matriz mat_13 es {mat_13.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_13 es {mat_13.shape}")
print(f"\nEl número de elementos de la matriz mat_13 es {mat_13.size}")

La matriz mat_13 es 
[[[ 57  21  48   0]
  [ 71  27  60   0]
  [111  51  96   0]]

 [[ 66  16  36  18]
  [ 95  22  58  29]
  [ 83  20  46  23]]

 [[ 44  34  72  44]
  [ 34  32  72  34]
  [ 13  25  64  13]]]

El objeto mat_13 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_13 es 3

El tamaño de las dimensiones de la matriz mat_13 es (3, 3, 4)

El número de elementos de la matriz mat_13 es 36


In [32]:
# Crear una matriz con la ayuda de numpy de 3D que tenga 6 matrices de 2 filas x 2 columnas
# Podemos usar la función arange() para generar los elementos de la matriz
mat_14 = np.arange(24).reshape(6,2,2)
# Las características de la matriz
print(f"La matriz mat_14 es \n{mat_14}")
print(f"\nEl objeto mat_14 es del tipo \n{type(mat_14)}")
print(f"\nEl número de dimensiones de la matriz mat_14 es {mat_14.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_14 es {mat_14.shape}")
print(f"\nEl número de elementos de la matriz mat_14 es {mat_14.size}")

La matriz mat_14 es 
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]

El objeto mat_14 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_14 es 3

El tamaño de las dimensiones de la matriz mat_14 es (6, 2, 2)

El número de elementos de la matriz mat_14 es 24


In [33]:
# Acceder a los elementos de una matriz 3D

print(f"Los elementos de la primera matriz mat_13 son \n{mat_13[0]}")
print(f"\nLos elementos de la segunda matriz mat_13 son \n{mat_13[1]}")
print(f"\nLos elementos de la tercera matriz mat_13 son \n{mat_13[2]}")

Los elementos de la primera matriz mat_13 son 
[[ 57  21  48   0]
 [ 71  27  60   0]
 [111  51  96   0]]

Los elementos de la segunda matriz mat_13 son 
[[66 16 36 18]
 [95 22 58 29]
 [83 20 46 23]]

Los elementos de la tercera matriz mat_13 son 
[[44 34 72 44]
 [34 32 72 34]
 [13 25 64 13]]


In [34]:
print(f"Los elementos de la primera fila y la primera matriz mat_13 son \n{mat_13[0][0]}")

Los elementos de la primera fila y la primera matriz mat_13 son 
[57 21 48  0]


In [35]:
print(f"Los elementos de la tercera fila de la segunda matriz mat_13 son \n{mat_13[1][2]}")

Los elementos de la tercera fila de la segunda matriz mat_13 son 
[83 20 46 23]


In [36]:
print(f"Los elementos de la tercera fila de la segunda matriz mat_13 son \n{mat_13[1][2][0]}")

Los elementos de la tercera fila de la segunda matriz mat_13 son 
83


In [37]:
print(f"El valor mínimo de la matriz mat_13 es {mat_13.min()}")
print(f"El valor máximo de la matriz mat_13 es {mat_13.max()}")
print(f"La suma de los elementos de la matriz mat_13 es {mat_13.sum()}")

El valor mínimo de la matriz mat_13 es 0
El valor máximo de la matriz mat_13 es 111
La suma de los elementos de la matriz mat_13 es 1535


## Operaciones matemáticas

In [38]:
mat_15 = np.array([[3,1],[2,7]])
# Las características de la matriz mat_15
print(f"La matriz es \n{mat_15}")
print(f"\nEl objeto es del tipo \n{type(mat_15)}")
print(f"\nEl número de dimensiones de la matriz es {mat_15.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz es {mat_15.shape}")
print(f"\nEl número de elementos de la matriz es {mat_15.size}")

La matriz es 
[[3 1]
 [2 7]]

El objeto es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz es 2

El tamaño de las dimensiones de la matriz es (2, 2)

El número de elementos de la matriz es 4


In [39]:
mat_16 = np.array([[4,2],[5,7]])
# Las características de la matriz mat_16
print(f"La matriz es \n{mat_16}")
print(f"\nEl objeto es del tipo \n{type(mat_16)}")
print(f"\nEl número de dimensiones de la matriz es {mat_16.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz es {mat_16.shape}")
print(f"\nEl número de elementos de la matriz es {mat_16.size}")

La matriz es 
[[4 2]
 [5 7]]

El objeto es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz es 2

El tamaño de las dimensiones de la matriz es (2, 2)

El número de elementos de la matriz es 4


In [40]:
# Suma de matrices por método directo
mat_17 = mat_15 + mat_16
# Las características de la matriz mat_17
print(f"La matriz es \n{mat_17}")
print(f"\nEl objeto es del tipo \n{type(mat_17)}")
print(f"\nEl número de dimensiones de la matriz es {mat_17.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz es {mat_17.shape}")
print(f"\nEl número de elementos de la matriz es {mat_17.size}")

La matriz es 
[[ 7  3]
 [ 7 14]]

El objeto es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz es 2

El tamaño de las dimensiones de la matriz es (2, 2)

El número de elementos de la matriz es 4


In [41]:
# Suma de matrices por método add
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLa matriz resultado de la suma es \n{np.add(mat_15,mat_16)}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

La matriz resultado de la suma es 
[[ 7  3]
 [ 7 14]]


In [42]:
# Resta de matrices
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLa matriz resultado de la resta es \n{mat_15-mat_16}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

La matriz resultado de la resta es 
[[-1 -1]
 [-3  0]]


In [43]:
# Resta de matrices con método subtract
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLa matriz resultado de la resta es \n{np.subtract(mat_15,mat_16)}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

La matriz resultado de la resta es 
[[-1 -1]
 [-3  0]]


In [44]:
# Multiplicar matrices (a nivel de posiciones)
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLa matriz resultado de la multiplicación es \n{np.multiply(mat_15,mat_16)}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

La matriz resultado de la multiplicación es 
[[12  2]
 [10 49]]


In [45]:
# Multiplicar matrices
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLa matriz resultado de la multiplicación es \n{mat_15.dot(mat_16)}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

La matriz resultado de la multiplicación es 
[[17 13]
 [43 53]]


In [46]:
mat_18 = np.array([[1,2],[3,4],[5,6]])
mat_19 = np.array([[1,2,3],[3,4,5]])

print(f"La matriz mat_18 es \n{mat_18}")
print(f"\nEl número de dimensiones de la matriz mat_18 es {mat_18.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_18 es {mat_18.shape}")

print(f"\nLa matriz mat_19 es \n{mat_19}")
print(f"\nEl número de dimensiones de la matriz mat_19 es {mat_19.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_19 es {mat_19.shape}")


La matriz mat_18 es 
[[1 2]
 [3 4]
 [5 6]]

El número de dimensiones de la matriz mat_18 es 2

El tamaño de las dimensiones de la matriz mat_18 es (3, 2)

La matriz mat_19 es 
[[1 2 3]
 [3 4 5]]

El número de dimensiones de la matriz mat_19 es 2

El tamaño de las dimensiones de la matriz mat_19 es (2, 3)


In [47]:
# Multiplicar matrices
print(f"La primera matriz es \n{mat_18}")
print(f"\nLa segunda matriz es \n{mat_19}")
print(f"\nLa matriz resultado de la multiplicación es \n{mat_18.dot(mat_19)}")
print(f"\nLa matriz resultado de la multiplicación es \n{mat_19.dot(mat_18)}")

La primera matriz es 
[[1 2]
 [3 4]
 [5 6]]

La segunda matriz es 
[[1 2 3]
 [3 4 5]]

La matriz resultado de la multiplicación es 
[[ 7 10 13]
 [15 22 29]
 [23 34 45]]

La matriz resultado de la multiplicación es 
[[22 28]
 [40 52]]


In [48]:
print(f"La primera matriz es \n{mat_18}")
print(f"\nLa segunda matriz es \n{mat_19}")
print(f"\nLa matriz resultado de la multiplicación es \n{mat_18+mat_19}")

La primera matriz es 
[[1 2]
 [3 4]
 [5 6]]

La segunda matriz es 
[[1 2 3]
 [3 4 5]]


ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [49]:
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLas matrices concatenadas \n{np.concatenate([mat_15,mat_16],axis=0)}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

Las matrices concatenadas 
[[3 1]
 [2 7]
 [4 2]
 [5 7]]


In [50]:
print(f"La primera matriz es \n{mat_15}")
print(f"\nLa segunda matriz es \n{mat_16}")
print(f"\nLas matrices concatenadas \n{np.concatenate([mat_15,mat_16],axis=1)}")

La primera matriz es 
[[3 1]
 [2 7]]

La segunda matriz es 
[[4 2]
 [5 7]]

Las matrices concatenadas 
[[3 1 4 2]
 [2 7 5 7]]


In [ ]:
# Multiplicar matrices
print(f"La primera matriz es \n{mat_19}")
print(f"\nLa segunda matriz es \n{mat_18}")
print(f"\nLa matriz resultado de la multiplicación es \n{mat_19.dot(mat_18)}")

La primera matriz es 
[[1 2 3]
 [3 4 5]]

La segunda matriz es 
[[1 2]
 [3 4]
 [5 6]]

La matriz resultado de la multiplicación es 
[[22 28]
 [40 52]]
